import * as fs from 'fs';
import * as path from 'path';

export class DockerfileGenerator {
  public generateDockerfile(
    nodeVersion: string,
    workDir: string = '/app'
  ): string {
    if (!nodeVersion || nodeVersion.trim() === '') {
      throw new Error('Node.js version is required and cannot be empty');
    }

    return `# Generated by cli-docker-runner
FROM node:${nodeVersion}-alpine

# Set working directory
WORKDIR ${workDir}

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev || npm install --production

# Copy project files
COPY . .

# Expose port (can be overridden)
EXPOSE 3000

# Default command (will be overridden)
CMD ["npm", "start"]
`;
  }

  public saveDockerfile(content: string, targetDir: string): string {
    const dockerfilePath = path.join(targetDir, 'Dockerfile.tmp');
    fs.writeFileSync(dockerfilePath, content);
    return dockerfilePath;
  }

  public generateDockerIgnore(): string {
    return `node_modules
npm-debug.log
.git
.gitignore
.env
.env.*
dist
coverage
.DS_Store
*.log
Dockerfile.tmp
`;
  }

  public saveDockerIgnore(targetDir: string): void {
    const dockerIgnorePath = path.join(targetDir, '.dockerignore');
    
    // Only create if doesn't exist
    if (!fs.existsSync(dockerIgnorePath)) {
      const content = this.generateDockerIgnore();
      fs.writeFileSync(dockerIgnorePath, content);
    }
  }
}
