import * as fs from 'fs';
import * as path from 'path';

export class DockerfileGenerator {
  public generateDockerfile(
    nodeVersion: string = '22',
    workDir: string = '/app',
    needsNodemon: boolean = true
  ): string {
    if (nodeVersion.trim() === '') {
      throw new Error('Node.js version is required and cannot be empty');
    }

    const nodemonInstall = needsNodemon 
      ? '# Install nodemon globally for live reload\nRUN npm install -g nodemon\n\n' 
      : '';

    return `# Generated by cli-docker-runner
FROM node:${nodeVersion}-alpine

${nodemonInstall}# Set working directory
WORKDIR ${workDir}

# Copy package files
COPY package*.json ./

# Copy .npmrc if it exists (for private registries and npm config)
COPY .npmrc* ./

# Install all dependencies (including dev)
RUN npm install

# Install additional Rollup platform-specific packages if needed
RUN if [ -f package.json ] && (grep -q '"rollup"' package.json || grep -q '"vite"' package.json); then \\
    echo "🔧 Detected Rollup/Vite project, installing platform-specific packages..."; \\
    npm install --save-dev \\
      @rollup/rollup-linux-arm64-musl \\
      @rollup/rollup-linux-x64-musl \\
      @rollup/rollup-linux-arm64-gnu \\
      @rollup/rollup-linux-x64-gnu \\
      @rollup/rollup-darwin-arm64 \\
      @rollup/rollup-darwin-x64 \\
      2>/dev/null || echo "⚠️  Some Rollup packages could not be installed (this is normal)"; \\
  fi

# Add node_modules/.bin to PATH for locally installed packages
ENV PATH="${workDir}/node_modules/.bin:$PATH"

# Copy project files
COPY . .

# Expose port (can be overridden)
EXPOSE 3000

# Default command (will be overridden)
CMD ["npm", "start"]
`;
  }

  public saveDockerfile(content: string, targetDir: string): string {
    const dockerfilePath = path.join(targetDir, 'Dockerfile.tmp');
    fs.writeFileSync(dockerfilePath, content);
    return dockerfilePath;
  }

  public generateDockerIgnore(): string {
    return `node_modules
npm-debug.log
.git
.gitignore
.env
.env.*
dist
coverage
.DS_Store
*.log
Dockerfile.tmp
`;
  }

  public saveDockerIgnore(targetDir: string): void {
    const dockerIgnorePath = path.join(targetDir, '.dockerignore');
    
    // Only create if doesn't exist
    if (!fs.existsSync(dockerIgnorePath)) {
      const content = this.generateDockerIgnore();
      fs.writeFileSync(dockerIgnorePath, content);
    }
  }
}
